### ISSUE TITLE
Bug: unable to play stream

### ISSUE THREAD

**Issue by lexterror** [eshaz/icecast-metadata-js#101]
Hi,

I am unable to play the following stream:

http://stream.syntheticfm.com:8040/stream

It does work with your average html5 player though...

Thank you!

**Comment by eshaz** [comment]
This is not a bug with this library. This link is HTTP, and it won't work if you're loading your webpage with HTTPS. Browsers block mixed content so that no unencrypted HTTP content will load on an encrypted HTTPS webpage. This cannot be disabled and there is no work around other than finding a link that uses HTTPS and has CORS configured properly, or serving your webpage as HTTP (not recommended).

Read [the troubleshooting section on this repo](https://github.com/eshaz/icecast-metadata-js#http-and-https-mixed-content) and [the MDN docs on this](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) for more info.

I haven't tried it, but it's possible that the mixed content restriction isn't applied to the `<audio>` element, which is what any HTML5 player would be using. However, this will only play the audio and will not provide any metadata during playback.
