### ISSUE TITLE
IcecastMetadataPlayer return net::ERR EMPTY_REPONSE

### ISSUE THREAD

**Issue by darkslayer96** [eshaz/icecast-metadata-js#146]
Hi, I'm trying to make an Ionic project for a stream radio. 

But when I call the player to play(). Its return on console
GET http://207.244.66.85:3537/stream net::ERR_EMPTY_RESPONSE.

Trying the example on the installation instructions works fine but no with my radio stream. I tried with Howler Js and its working but I need the metadata from the stream. please help
I'm attaching the method that I am using.

`  start(){

    const player = new IcecastMetadataPlayer(
      "http://207.244.66.85:3537/stream",
      { onMetadata: (metadata:any) => {console.log(metadata)} }
    );

    player.play();
  }`

Sorry for my bad english

**Comment by eshaz** [comment]
Which streaming service and version are you using?

I did notice that your endpoint is HTTP. If your website is hosted through HTTPS then you will need to update your stream to also be through HTTPS due to mixed content security restrictions enforced in the browser.

There can also be issues with CORS that may have different error results across platforms. This is described in the troubleshooting section of the main readme of this repo.

Can you try one of the stream endpoints in the demo for this repo in your website and see if it works? If one of these streams work, we should be able to rule out any issues with your Ionic build toolchain.

**Comment by darkslayer96** [comment]
I'm using an Icecast 2.4.3 server via listen2myradio.com. Its a free shoutcast service.

the demo endpoints works fine.

**Comment by darkslayer96** [comment]
Hi finally I fixed it. It was a CORS error. So I'm closing it.

Thank you! 
and sorry for the trouble

**Comment by highon10kyears** [comment]
I'm experiencing the same issue, with the CORS headers listed on the troubleshooting page added to my Icecast XML file and to my Apache server's directory configs; I've also tried removing the headers from one or the other and neither configuration has fixed it; on Chrome it reports this "EMPTY_RESPONSE" error, on Firefox it's blocked + CORS request did not succeed + status code null
