### ISSUE TITLE
[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead

### ISSUE THREAD

**Issue by Yahav** [eshaz/icecast-metadata-js#162]
Should probably update it for future proofing.
https://github.com/eshaz/icecast-metadata-js/blob/57c2bedc99ece498df2591debc637e782f3ac598/src/icecast-metadata-player/src/IcecastMetadataPlayer.js#L554

**Comment by eshaz** [comment]
This is here so on iOS the AudioContext that's used for WebAudio playback always remains running. Last time I tested, the AudioContext will stop working if this isn't here. If the AudioContext stops, WebAudio playback won't work.

If there's a better way to do this, I would gladly add it in! Closing for now since there's not a better alternative at this time.
