### ISSUE TITLE
Creating a "slim", player only package without metadata

### ISSUE THREAD

**Issue by Yahav** [eshaz/icecast-metadata-js#163]
So, you've created a cross-platform, cross-encoding stream player with a unified API here which is not something to be taken lightly.
I feel like there should be a version of this which is simply and only the streaming playing capabilities, stripping the whole metadata related dependencies and code could make the package really lightweight which is very desirable. 
Will you consider this? I might be able to sponsor this fork as well should you decide its a good idea.

**Comment by eshaz** [comment]
I think this is a good idea. I'm thinking it could be implemented slightly differently though.

The bulk of the code size is consumed by the [`wasm-audio-decoders`](https://github.com/eshaz/wasm-audio-decoders) and the [`synaudio`](https://github.com/eshaz/synaudio) libraries. The metadata functionality is actually quite small in comparison, probably less than 10kB.

I think it would be good to have these features able to be selectively enabled / disabled so that when they are disabled, the extra code isn't bundled when used with a bundler such as webpack or rollup.

One main example would be that if you only ever use Opus for your stream, you won't need the MP3 or FLAC decoders, which would save about 150kB. Or if you don't want iOS support / WebAudio, you could remove the decoders altogether.

This kind of change would require some significant refactoring of the existing code, but I'll take a look at this.

**Comment by Yahav** [comment]
@eshaz Is there anyway we can have a quick conversation about that?

**Comment by eshaz** [comment]
We can, but I would prefer to use this issue thread so that others can reference this in the future. Will that work?

**Comment by Yahav** [comment]
> I think it would be good to have these features able to be selectively enabled / disabled so that when they are disabled, the extra code isn't bundled when used with a bundler such as webpack or rollup.
> 
> One main example would be that if you only ever use Opus for your stream, you won't need the MP3 or FLAC decoders, which would save about 150kB. Or if you don't want iOS support / WebAudio, you could remove the decoders altogether.
> 

You are absolutely right, that is even better :)
If we're going this route, imho the best way to achieve that is not to pre-configure which modules/decoders/mechanisms you're going to use, but rather have them dyanmically imported on a "need" basis, for instance, if an Opus stream is initiated and we're on a platform that doesn't support native playback, await import() the desired module to handle this situation, same goes for the metadata mechanisms and cross-play feature.

**Comment by eshaz** [comment]
@Yahav, it turns out the `await import()` solution works great with webpack.

If you want to take a look, I have #164 that splits the `icecast-metadata-player` into separate files that are downloaded as needed by the library. This should allow for a bit less data to be loaded on the initial page load.

**Comment by Yahav** [comment]
Amazing! I'll have a look into this later this week.
This dynamic import loads the different kind of encoders, how about the rest of the optional mechanisms, like the metadata fetching, are those something that you might be able to dynamically import as well?

**Comment by Yahav** [comment]
Not sure if that's intended. but when setting the playback method to html5, the mediasource.js file is loaded anyway.

**Comment by eshaz** [comment]
It should be good as is. That file is needed for the WASM audio decoders to function, so it all needs to load if one of the decoders is also needed.

**Comment by Yahav** [comment]
@eshaz ok.
What about that one though: 
https://github.com/eshaz/icecast-metadata-js/issues/163#issuecomment-1518690986

**Comment by eshaz** [comment]
It preloads since most browsers use mediasource by default (everything except iOS), and then loads it again from cache in the `import`. The preload made starting playback a bit more responsive at the cost of just a few extra KB downloaded for iOS users.
