### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by bryannso** [eshaz/icecast-metadata-js#202]
Trying to run this locally, and I'm getting ERR_EMPTY_RESPONSE when PlayerFactory.js attempts fetchStream.  (Line 135).

Stream URL:  http://feeds.baycountyscanner.org:8010/scanner.mp3

Testing page: http://www.[baycountyscanner.org/mplayer.html

**Comment by eshaz** [comment]
It looks like your stream doesn't have CORS properly enabled and is returning the error when the browser attempts to request the OPTIONS method. You will need to properly set up CORS if you want ICY metadata. I you don't / can't setup CORS, then you should be able to play the stream with ICY metadata disabled (setting `metadataTypes: []` will disable ICY metadata).

CORS setup: https://github.com/eshaz/icecast-metadata-js?tab=readme-ov-file#cors
Metadata options: https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-player#metadata-options

**Comment by JordanTroutman** [comment]
I'm having the same issue with ICY metadata and it works on curl but not on the browser. I also tried streaming my radio via the demo version that's online and it doesn't work there. It might be an issue with the way my server is set up? Can you provide a link to how you set up your icecast server?

**Comment by eshaz** [comment]
@JordanTroutman Usually the issue with ICY metadata is caused by CORS misconfiguration. A more complete description is linked above and in the readme of this repo. I use Nginx to proxy my Icecast server, and the example is also linked above.  There are other ways to do this as well. You should consult the Icecast docs for more information on how to configure Icecast itself.
