### ISSUE TITLE
CORS Issue with metadata

### ISSUE THREAD

**Issue by mhankosky** [eshaz/icecast-metadata-js#42]
Using the plugin to stream a ICECAST2 Stream, The meta Data will not load on Chrome:
`Falling back to HTML5 audio with no metadata updates. See the console for details on the error.
`
Chrome Developer JS Console:
`Access to fetch at 'http://ICESERVERIP:8000/STREAM.mp3' from origin 'http://WEBSERVERIP' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Doing some research has lead to this for normal HTML5 Audio Player to disable CORS.  Is there a way to implement this into the JS?

```
<audio controls crossorigin="anonymous">
<source src="http://myicecastserver.dns/mount" type="audio/mpeg" />
</audio>
```

**Comment by eshaz** [comment]
Unfortunately there is no way to work around CORS and also be able to read the metadata from the response, because it requires the response to be readable by the JavaScript code.

If you have access to do so, you can add the cross origin headers to your Icecast server configuration as described [here](https://github.com/eshaz/icecast-metadata-js#cors). Another option is that you could proxy the Icecast resource through your webserver to both put it on the same origin and add the CORS headers if you need to.
