### ISSUE TITLE
onStream, onError seemingly fail to be invoked

### ISSUE THREAD

**Issue by xunkar** [eshaz/icecast-metadata-js#46]
I've been able to use the player, get audio, and parse incoming metadata events. However, onStream and onError do not seem to produce any result. I'm looking for a way to detect whenever the stream goes down for instance, and I thought onError could do just that (and I suppose onStream could notify when the stream is back up). However if the player is playing and I cut the stream, onError is not triggered. Furthermore onStream never seems to be triggered by any event.

    const player = new IcecastMetadataPlayer(endpoint, { 
       onStream: (input) => { console.log(input); }, 
       onError: (input) => { console.log(input); },
       onMetadata: (input) => { onMetadata(input); }, 
       metadataTypes: ['ogg'] 
    });

**Comment by eshaz** [comment]
Thanks for submitting an issue on this.

The `onStream` callback not being invoked at all is a bug, and I'll address that in #47.

Currently, the `onError` callback doesn't get called when the stream ends due to the connection being dropped after a successful response, but that makes sense to do so. I added #48 to make this update.

The functionality your talking about to listen to the `onStream` callback to detect when it goes back up, would imply some retry / reconnect logic which would be an enhancement. Currently, there is no retry logic and stream will not restart if there is a failure or connection drop. I added #49 to make that enhancement. You can use the new `onStreamStart` callback that should be added in #48 to know when a stream comes back up after retrying.
