### ISSUE TITLE
Some stations don't show metadata

### ISSUE THREAD

**Issue by lexterror** [eshaz/icecast-metadata-js#66]
I have 3 stations that don't show metadata. If you have time maybe you can let me know if I can do anything about it. 

Thank you!

The 3 stations are: 

Radio Schizoid: http://94.130.113.214:8000/chill
Classic FM: https://media-ssl.musicradio.com/ClassicFM
IBGR: http://ibizaglobalradio.streaming-pro.com:8024/

**Comment by eshaz** [comment]
Could you try entering the stations into the [html demo](https://eshaz.github.io/icecast-metadata-js/demo.html) page? In that page, you can open up the browser's dev console and see if there are any errors or warnings shown. You can then look at the [Troubleshooting](https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-player#troubleshooting) section which describes some common causes and solutions for any error messages.

Let me know if that helps.

**Comment by lexterror** [comment]
Two stations say "Loading..." and the metadata never shows. And one says "failed to fetch." 

All 3 stations are "ogg" (and I've also tried metadata.ARTIST / metadata.ALBUM / metadata.TITLE)

**Comment by eshaz** [comment]
Do you have any output from the console or network tab in your browser?

If the streams are ogg, you'll have to deselect the ICY checkbox and select the OGG checkbox. This just changes the `metadataTypes` array that is passed into the options parameter on IcecastMetadataPlayer.

**Comment by lexterror** [comment]
I've looked at the documentation and most of my stations are working (both "Icy" and "ogg" streams)

These particular stations for some reason don't show any metadata...

**Comment by eshaz** [comment]
If you can take a look at your console and network tabs in Chrome's dev tools, that should give you some more information to work from.

**Comment by lexterror** [comment]
Everything seems ok, no errors...

**Comment by eshaz** [comment]
I tried out the stations you have. These are all failing because of CORS errors. You can try these yourself, and look at the network tab to confirm. Unfortunately, there is no way to support cross-orgin ICY metadata from stations that don't have CORS configured to allow cross-origin / the Icy-Metadata header, since this is a browser enforced security feature. These streams play in a desktop app because CORS is not being enforced by the app your using. See https://github.com/eshaz/icecast-metadata-js#cors for more information.

CORS Icy-Metadata header not allowed. Works without Icy-Metadata header.
http://94.130.113.214:8000/chill - MP3
https://media-ssl.musicradio.com/ClassicFM - AAC
https://kathy.torontocast.com:1825/stream - MP3

CORS Cross Origin not allowed: Doesn't work cross-origin.
http://ibizaglobalradio.streaming-pro.com:8024/
