### ISSUE TITLE
iOS 15 Web Audio Playback Stops while locked

### ISSUE THREAD

**Issue by eshaz** [eshaz/icecast-metadata-js#97]
### Problem

Web Audio playback stops after playing for a few minutes after the screen is locked on iOS 15 simulator. This issue was not present in iOS 14.8.

### Workaround

Set the `playbackMethod` to `"html5"` when instantiating.

```js
new IcecastMetadataPlayer("https://example.com/stream", {
  playbackMethod: "html5"
});
```

**Comment by BajakiGabesz** [comment]
This problem also happens on a regular Chrome browser. I listened to a stream and it stops after 16 minutes. It has happened multiple times and it almost happened at the exact same time.
Maybe, it is important info to you, it is happening right after metadata is changed or when a new audio item comes. If I set the playback method to html5 it is also working properly.
Anyhow, on my side when setting the playbackMethod to html5 there is no sound at all on iOS 14.8 but it looks like it is playing the stream because the state is changing to playing.

**Comment by eshaz** [comment]
@BajakiGabesz Thanks for reporting the additional issue with Chrome! I've found that problem and will release a fix shortly. It's unfortunately not related to the iOS issue through.

**Comment by eshaz** [comment]
Further debugging on iOS 15.0 simulator shows that the `AudioContext.currentTime` is incrementing about 10% faster than the actual audio playback rate which is causing a mismatch between the buffer source start time and the audio context time. This is either a bug in iOS 15.0 or the simulator.

However, this issue is not present in iOS 15.2 simulator and playback works fine when locked for extended periods.

### Solution
Upgrade to at least iOS 15.2 :)
